-- Restore the built-in Venezuela Relief starter organizations into Supabase.
-- Paste this whole file into Supabase SQL Editor and click Run.
-- It updates organizations with the same slug and inserts missing ones.

insert into public.organizations (
  slug,
  display_name,
  legal_name,
  logo_url,
  donation_url,
  help_types,
  donor_regions,
  trust_level,
  priority_score,
  priority_note,
  summary_en,
  summary_es,
  what_they_do_en,
  what_they_do_es,
  who_can_help_en,
  who_can_help_es,
  aid_route_en,
  aid_route_es,
  evidence_links,
  risk_notes_en,
  risk_notes_es,
  last_checked,
  status
)
values
  ('direct-relief', 'Direct Relief', 'US nonprofit medical aid', null, 'https://donate.directrelief.org/give/647931#!/donation/checkout', array['money', 'medical', 'tax', 'europe']::text[], array['US', 'Europe', 'Global']::text[], 'verified_nonprofit', 100, 'Top medical aid route with Venezuela-specific response page.', 'Medical aid, emergency grants, and supplies for health responders.', 'Ayuda medica, fondos de emergencia e insumos para respuesta de salud.', 'Launched a Venezuela earthquake response with emergency grants and planned medical shipments for hospitals, clinics, and responders.', 'Inicio una respuesta al terremoto con fondos de emergencia y envios medicos para hospitales, clinicas y equipos de respuesta.', 'Individuals, companies, and foundations that want a health-focused, US-receipted route.', 'Personas, empresas y fundaciones que buscan una ruta medica con recibo en EEUU.', 'Direct Relief -> Medical Impact, Bomberos Unidos Sin Fronteras, and health facilities needing medical supplies.', 'Direct Relief -> Medical Impact, Bomberos Unidos Sin Fronteras y centros de salud que necesitan insumos.', '[{"label":"Response page","href":"https://www.directrelief.org/2026/06/venezuela-earthquake-direct-relief-emergency-response/"}]'::jsonb, 'Strong medical option. Donors who want restricted giving should use the Venezuela response page and save the receipt.', 'Opcion fuerte para ayuda medica. Donantes que quieren restringir su aporte deben usar la pagina de Venezuela y guardar el recibo.', '2026-06-27', 'approved'),
  ('world-central-kitchen', 'World Central Kitchen', 'Food relief nonprofit', null, 'https://donate.wck.org/', array['money', 'food', 'tax', 'europe']::text[], array['US', 'Europe', 'Global']::text[], 'verified_nonprofit', 96, 'Top food-relief route with active field updates.', 'Fresh meals, water, and mobile food support for affected communities.', 'Comidas frescas, agua y apoyo movil de alimentos para comunidades afectadas.', 'Reports teams serving meals after the Caracas-area earthquakes, including hot meals, sandwiches, water, and community kitchens.', 'Reporta equipos sirviendo comida tras los terremotos cerca de Caracas, incluyendo platos calientes, sandwiches, agua y cocinas comunitarias.', 'Donors who want immediate food relief through a known disaster food-response organization.', 'Donantes que quieren ayuda alimentaria inmediata mediante una organizacion conocida de respuesta a desastres.', 'WCK response teams and local food partners serving affected neighborhoods.', 'Equipos de WCK y aliados locales de comida en zonas afectadas.', '[{"label":"Response page","href":"https://wck.org/relief/caracas-venezuela-earthquakes-2026/"}]'::jsonb, 'Good for meals. Review latest updates if donors need proof of active field distribution by city.', 'Buena opcion para comidas. Revisar ultimas actualizaciones si el donante necesita prueba por ciudad.', '2026-06-27', 'approved'),
  ('ifrc-venezuelan-red-cross', 'IFRC + Venezuelan Red Cross', 'Red Cross network', null, 'https://donate.redcrossredcrescent.org/', array['money', 'food', 'medical', 'volunteer', 'europe']::text[], array['Venezuela', 'Europe', 'Global']::text[], 'field_partner_verified', 92, 'Strong field route through Venezuelan Red Cross.', 'Shelter, health, cash assistance, water, sanitation, and protection.', 'Refugio, salud, asistencia en efectivo, agua, saneamiento y proteccion.', 'The IFRC emergency appeal supports the Venezuelan Red Cross response across shelter, health, cash, WASH, and protection services.', 'El llamado de emergencia de IFRC apoya a la Cruz Roja Venezolana en refugio, salud, efectivo, agua/saneamiento y proteccion.', 'Global donors and people who want to support the national Red Cross response directly.', 'Donantes globales y personas que quieren apoyar directamente a la Cruz Roja nacional.', 'IFRC emergency appeal -> Venezuelan Red Cross branches and volunteers.', 'Llamado de emergencia IFRC -> sedes y voluntarios de Cruz Roja Venezolana.', '[{"label":"Emergency appeal","href":"https://www.ifrc.org/emergency/venezuela-earthquake-2026"}]'::jsonb, 'Excellent field route, but label clearly for non-US-tax-deductible giving unless a US fiscal route is confirmed.', 'Ruta de campo fuerte, pero etiquetar claramente como no deducible en EEUU salvo que se confirme ruta fiscal en EEUU.', '2026-06-27', 'approved'),
  ('unicef-usa', 'UNICEF USA', 'Children and family support', null, 'https://www.unicefusa.org/donate', array['money', 'food', 'medical', 'tax', 'europe']::text[], array['US', 'Europe', 'Global']::text[], 'verified_nonprofit', 88, 'Child-focused emergency support.', 'Emergency support for children, families, water, sanitation, health, and education.', 'Apoyo de emergencia para ninos, familias, agua, saneamiento, salud y educacion.', 'UNICEF USA highlights urgent needs for children after the earthquakes, including WASH, health, psychosocial support, and temporary learning spaces.', 'UNICEF USA destaca necesidades urgentes de ninos tras los terremotos: agua/saneamiento, salud, apoyo psicosocial y espacios educativos temporales.', 'Donors who want a child-focused route and an established US charity receipt.', 'Donantes que quieren una ruta enfocada en ninos y recibo de una organizacion de EEUU.', 'UNICEF country response and partners serving children and families in affected areas.', 'Respuesta de UNICEF y aliados que atienden ninos y familias en zonas afectadas.', '[{"label":"Response page","href":"https://www.unicefusa.org/stories/venezuela-earthquakes-children-need-help-now"}]'::jsonb, 'Strong for child-focused aid. Confirm whether donation is country-restricted or supports broader UNICEF emergency work.', 'Fuerte para ayuda a ninos. Confirmar si la donacion es solo para Venezuela o para emergencias UNICEF mas amplias.', '2026-06-27', 'approved'),
  ('international-rescue-committee', 'International Rescue Committee', 'Emergency relief nonprofit', null, 'https://help.rescue.org/donate/venezuela-earthquake', array['money', 'food', 'medical', 'children', 'tax', 'europe']::text[], array['US', 'Europe', 'Global']::text[], 'verified_nonprofit', 86, 'Broad emergency response route.', 'Emergency medical care, clean water, shelter, cash, and protection support.', 'Atencion medica, agua limpia, refugio, efectivo y proteccion.', 'IRC says gifts support teams delivering emergency medical care, clean water, shelter, cash, protection, and recovery help.', 'IRC indica que las donaciones apoyan equipos con salud de emergencia, agua limpia, refugio, efectivo, proteccion y recuperacion.', 'Donors who want a broad emergency-response organization with US and global donation routes.', 'Donantes que buscan una organizacion amplia de respuesta de emergencia con rutas en EEUU y globales.', 'IRC emergency response teams and partners serving affected communities.', 'Equipos de emergencia de IRC y aliados que atienden comunidades afectadas.', '[{"label":"Response page","href":"https://www.rescue.org/article/how-help-survivors-earthquakes-venezuela"}]'::jsonb, 'The appeal language may support Venezuela and other crises. Check the donation page if a donor wants Venezuela-only restriction.', 'El llamado puede apoyar Venezuela y otras crisis. Revisar la pagina si el donante quiere restriccion solo Venezuela.', '2026-06-27', 'approved'),
  ('airlink', 'Airlink', 'Humanitarian logistics', null, 'https://airlinkflight.org/get-involved/donate/', array['money', 'medical', 'food', 'europe']::text[], array['Europe', 'Global']::text[], 'field_partner_verified', 72, 'Useful logistics route, not direct household aid.', 'Air transport and logistics for responders, cargo, and emergency supplies.', 'Transporte aereo y logistica para equipos, carga e insumos de emergencia.', 'Airlink reports mobilizing flights and logistics for humanitarian partners responding to the Venezuela earthquakes.', 'Airlink reporta vuelos y logistica para aliados humanitarios que responden a los terremotos en Venezuela.', 'Donors who want to fund logistics, cargo movement, and responder transport rather than direct family aid.', 'Donantes que quieren financiar logistica, carga y transporte de equipos, no ayuda directa familiar.', 'Airlink -> airline/logistics partners -> vetted humanitarian response organizations.', 'Airlink -> aliados aereos/logisticos -> organizaciones humanitarias verificadas.', '[{"label":"Response page","href":"https://airlinkflight.org/response/venezuela-earthquakes/"}]'::jsonb, 'Best for logistics-minded donors. It is not a direct food, shelter, or cash-transfer route.', 'Mejor para donantes enfocados en logistica. No es ruta directa de comida, refugio o efectivo.', '2026-06-27', 'approved'),
  ('givedirectly', 'GiveDirectly', 'Cash assistance', null, 'https://donate.givedirectly.org/', array['money', 'tax', 'europe']::text[], array['US', 'Europe', 'Global']::text[], 'verified_nonprofit', 80, 'Cash route with implementation caveats.', 'Cash transfers for affected families, with public caveats on implementation.', 'Transferencias de efectivo a familias afectadas, con advertencias publicas sobre implementacion.', 'GiveDirectly is assessing cash delivery with partners. Its page explains recipient targeting, intended payments, and fallback use of funds.', 'GiveDirectly evalua entrega de efectivo con aliados. Su pagina explica seleccion de beneficiarios, pagos previstos y uso alternativo de fondos.', 'Donors who prefer direct cash to affected households and accept program-start risk.', 'Donantes que prefieren efectivo directo a hogares afectados y aceptan riesgo de inicio del programa.', 'GiveDirectly and partners identify affected families, then send cash transfers where feasible.', 'GiveDirectly y aliados identifican familias afectadas y envian transferencias cuando sea viable.', '[{"label":"Campaign page","href":"https://www.givedirectly.org/venezuela-earthquakes?ref=home"}]'::jsonb, 'Transparent but not yet guaranteed: if cash cannot be delivered, funds may move to future emergency responses.', 'Transparente pero no garantizado: si no pueden entregar efectivo, los fondos podrian ir a futuras emergencias.', '2026-06-27', 'approved'),
  ('save-the-children', 'Save the Children', 'Children and family relief', null, 'https://support.savethechildren.org/', array['money', 'food', 'medical', 'children', 'tax', 'europe']::text[], array['US', 'Europe', 'Global']::text[], 'verified_nonprofit', 82, 'Child and family emergency support.', 'Emergency supplies, shelter, food, water, and child protection support.', 'Insumos de emergencia, refugio, comida, agua y proteccion infantil.', 'The Venezuela page says donations help deliver shelter, food, clean water, protection services, and psychosocial support after the earthquakes.', 'La pagina de Venezuela indica que las donaciones apoyan refugio, comida, agua limpia, proteccion y apoyo psicosocial tras los terremotos.', 'Donors who want a child-focused emergency charity with a broad disaster response model.', 'Donantes que quieren una organizacion enfocada en ninos y respuesta amplia a desastres.', 'Save the Children emergency response and partners supporting children and families.', 'Respuesta de Save the Children y aliados que apoyan ninos y familias.', '[{"label":"Response page","href":"https://www.savethechildren.org/us/where-we-work/venezuela"}]'::jsonb, 'Good family support option. Review gift designation if a donor wants only Venezuela earthquake use.', 'Buena opcion para familias. Revisar designacion si el donante quiere uso solo para Venezuela.', '2026-06-27', 'approved'),
  ('americares', 'Americares', 'Emergency health response', null, 'https://www.americares.org/WWDisaster', array['money', 'medical', 'tax', 'europe']::text[], array['US', 'Europe', 'Global']::text[], 'verified_nonprofit', 84, 'Health-focused emergency supplies route.', 'Medicines, supplies, hygiene kits, emergency funding, and health system support.', 'Medicinas, insumos, kits de higiene, fondos de emergencia y apoyo al sistema de salud.', 'Americares reports emergency funding, medicines, medical supplies, hygiene kits, and local health partner support.', 'Americares reporta fondos de emergencia, medicinas, insumos medicos, kits de higiene y apoyo a aliados locales de salud.', 'Donors who want a health and emergency-supplies route from a US nonprofit.', 'Donantes que quieren una ruta de salud e insumos de emergencia desde una ONG de EEUU.', 'Americares -> local health partners, clinics, and emergency responders.', 'Americares -> aliados locales de salud, clinicas y equipos de emergencia.', '[{"label":"Response page","href":"https://www.americares.org/news/americares-responds-to-venezuela-earthquakes/"}]'::jsonb, 'Donation route may be a worldwide disaster fund. Flag clearly if it is not restricted to Venezuela only.', 'La donacion puede entrar a un fondo mundial de desastres. Marcarlo claro si no es solo Venezuela.', '2026-06-27', 'approved'),
  ('catholic-relief-services', 'Catholic Relief Services', 'US nonprofit with Caritas route', null, 'https://www.crs.org/donate/venezuela-earthquake?ms=agicrs0226veq00her00', array['money', 'food', 'medical', 'tax', 'europe']::text[], array['US', 'Europe', 'Global']::text[], 'field_partner_verified', 78, 'Caritas-linked route for faith communities.', 'Cash, shelter kits, hygiene supplies, food parcels, and psychosocial support.', 'Efectivo, kits de refugio, higiene, paquetes de comida y apoyo psicosocial.', 'CRS says donations support Caritas Venezuela with cash assistance, shelter kits, hygiene supplies, food parcels, and psychosocial support.', 'CRS indica que las donaciones apoyan a Caritas Venezuela con efectivo, refugio, higiene, comida y apoyo psicosocial.', 'US donors, faith communities, parishes, and institutions that want a Caritas-linked route.', 'Donantes en EEUU, comunidades de fe, parroquias e instituciones que buscan una ruta vinculada a Caritas.', 'CRS -> Caritas Venezuela -> households and communities affected by the earthquakes.', 'CRS -> Caritas Venezuela -> hogares y comunidades afectadas por los terremotos.', '[{"label":"Response page","href":"https://www.crs.org/donate/venezuela-earthquake?ms=agicrs0226veq00her00"}]'::jsonb, 'Good route for faith communities. Confirm latest Caritas field update before featuring as top recommendation.', 'Buena ruta para comunidades de fe. Confirmar actualizacion de campo de Caritas antes de destacarla.', '2026-06-27', 'approved'),
  ('global-empowerment-mission', 'Global Empowerment Mission', 'Miami-based emergency response', null, 'https://give.gem.org/', array['money', 'food', 'dropoff', 'volunteer', 'tax']::text[], array['US', 'Miami', 'Global']::text[], 'verified_nonprofit', 76, 'Good for supply drives and Miami-area action.', 'Supplies, transport, local coordination, volunteer support, and supply drives.', 'Insumos, transporte, coordinacion local, voluntariado y centros de acopio.', 'GEM has a Venezuela earthquakes mission page and is relevant for donors or volunteers near Miami looking for supply-drive routes.', 'GEM tiene una pagina de mision para los terremotos y sirve para donantes o voluntarios cerca de Miami buscando rutas de insumos.', 'US donors, Miami-area volunteers, supply partners, and companies with in-kind goods.', 'Donantes en EEUU, voluntarios en Miami, aliados de insumos y empresas con donaciones en especie.', 'GEM mission team, local partners, and shipping/supply networks supporting affected communities.', 'Equipo de mision GEM, aliados locales y redes de envio e insumos para comunidades afectadas.', '[{"label":"Mission page","href":"https://www.globalempowermentmission.org/mission/venezuela-earthquakes/"}]'::jsonb, 'Useful for local action. Verify current drop-off address, accepted items, and shipment proof before promoting supply drives.', 'Util para accion local. Verificar direccion, articulos aceptados y prueba de envio antes de promover centros de acopio.', '2026-06-27', 'approved')
on conflict (slug) do update set
  display_name = excluded.display_name,
  legal_name = excluded.legal_name,
  logo_url = excluded.logo_url,
  donation_url = excluded.donation_url,
  help_types = excluded.help_types,
  donor_regions = excluded.donor_regions,
  trust_level = excluded.trust_level,
  priority_score = excluded.priority_score,
  priority_note = excluded.priority_note,
  summary_en = excluded.summary_en,
  summary_es = excluded.summary_es,
  what_they_do_en = excluded.what_they_do_en,
  what_they_do_es = excluded.what_they_do_es,
  who_can_help_en = excluded.who_can_help_en,
  who_can_help_es = excluded.who_can_help_es,
  aid_route_en = excluded.aid_route_en,
  aid_route_es = excluded.aid_route_es,
  evidence_links = excluded.evidence_links,
  risk_notes_en = excluded.risk_notes_en,
  risk_notes_es = excluded.risk_notes_es,
  last_checked = excluded.last_checked,
  status = 'approved',
  updated_at = now();

select slug, display_name, status, priority_score
from public.organizations
where slug in ('direct-relief', 'world-central-kitchen', 'ifrc-venezuelan-red-cross', 'unicef-usa', 'international-rescue-committee', 'airlink', 'givedirectly', 'save-the-children', 'americares', 'catholic-relief-services', 'global-empowerment-mission')
order by priority_score desc, display_name asc;
